# Generated by Django 4.1.1 on 2022-11-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bike_station_review_bike_station_id_bike_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='price',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
