# Generated by Django 4.0.4 on 2022-11-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_booking_bike_id_alter_booking_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='price',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
    ]
